/**
 * Password reset token storage.
 * 
 * Stores password reset codes generated by the website (not from License Engine).
 * Separates email verification from password update, preventing License Engine exposure.
 *
 * Development default: in-process MemoryStore.
 * Production (horizontal scale): set UPSTASH_REDIS_REST_URL + UPSTASH_REDIS_REST_TOKEN
 */

export interface PasswordResetData {
  email: string;
  createdAt: number;
  origin: "website" | "erp";
}

export interface PasswordResetStore {
  set(key: string, data: PasswordResetData, ttlMs: number): Promise<void>;
  get(key: string): Promise<PasswordResetData | null>;
  delete(key: string): Promise<void>;
}

class MemoryPasswordResetStore implements PasswordResetStore {
  private data = new Map<string, { value: PasswordResetData; expiresAt: number }>();

  async set(key: string, data: PasswordResetData, ttlMs: number): Promise<void> {
    this.data.set(key, {
      value: data,
      expiresAt: Date.now() + ttlMs,
    });
  }

  async get(key: string): Promise<PasswordResetData | null> {
    const entry = this.data.get(key);
    if (!entry) return null;
    if (Date.now() > entry.expiresAt) {
      this.data.delete(key);
      return null;
    }
    return entry.value;
  }

  async delete(key: string): Promise<void> {
    this.data.delete(key);
  }
}

/**
 * Upstash Redis REST adapter for password reset storage.
 */
class UpstashRestPasswordResetStore implements PasswordResetStore {
  constructor(
    private readonly baseUrl: string,
    private readonly token: string
  ) {}

  private async command(parts: (string | number)[]): Promise<unknown> {
    const res = await fetch(this.baseUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${this.token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(parts.map(String)),
      cache: "no-store",
    });
    if (!res.ok) {
      throw new Error(`Password reset store HTTP ${res.status}`);
    }
    const json = (await res.json()) as { result?: unknown };
    return json.result;
  }

  async set(key: string, data: PasswordResetData, ttlMs: number): Promise<void> {
    const redisKey = `pwd-reset:${key}`;
    const ttlSec = Math.max(1, Math.ceil(ttlMs / 1000));
    const jsonValue = JSON.stringify(data);
    
    try {
      await this.command(["SET", redisKey, jsonValue, "EX", ttlSec]);
    } catch {
      throw new Error("Failed to store password reset code");
    }
  }

  async get(key: string): Promise<PasswordResetData | null> {
    const redisKey = `pwd-reset:${key}`;
    try {
      const result = await this.command(["GET", redisKey]);
      if (!result) return null;
      return JSON.parse(String(result)) as PasswordResetData;
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    const redisKey = `pwd-reset:${key}`;
    try {
      await this.command(["DEL", redisKey]);
    } catch {
      // Silently ignore deletion errors
    }
  }
}

let cachedStore: PasswordResetStore | null = null;

export function getPasswordResetStore(): PasswordResetStore {
  if (cachedStore) return cachedStore;

  const url = process.env.UPSTASH_REDIS_REST_URL?.trim();
  const token = process.env.UPSTASH_REDIS_REST_TOKEN?.trim();
  const preferDistributed =
    process.env.RATE_LIMIT_STORE === "redis" ||
    process.env.RATE_LIMIT_STORE === "upstash" ||
    Boolean(url && token);

  if (preferDistributed && url && token) {
    cachedStore = new UpstashRestPasswordResetStore(url.replace(/\/+$/, ""), token);
  } else {
    cachedStore = new MemoryPasswordResetStore();
  }

  return cachedStore;
}

export function setPasswordResetStore(store: PasswordResetStore | null) {
  cachedStore = store;
}
